/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:1f6aa161-a823-49c9-add9-30818531014d",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_d412OhKTl",
    "aws_user_pools_web_client_id": "tg569r2g7crt56421fiejod02",
    "oauth": {}
};


export default awsmobile;
